AWSTemplateFormatVersion: "2010-09-09"

Description: aws-study-template

Parameters:
  KeyName:
    Description: The EC2 KeyPair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
    
Resources:
  
  AwsStudyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: aws-study-VPC

  AwsStudyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-internet-gateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref AwsStudyVPC
      InternetGatewayId: !Ref AwsStudyInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref AwsStudyVPC
      Tags:
        - Key: Name
          Value: aws-study-rtb-public

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref AwsStudyInternetGateway


  PublicSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref AwsStudyPublicSubnet
        RouteTableId: !Ref PublicRouteTable

  AwsStudyEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref AwsStudyVPC
      GroupName: aws-study-EC2-SG
      GroupDescription: aws-study-EC2-SG created 2025-04-21
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-ec2-sg
  
  AwsStudyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AwsStudyVPC
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-subnet

  AwsStudyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05206bf8aecfc7ae6
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref AwsStudyPublicSubnet
          GroupSet:
            -  !Ref AwsStudyEC2SG
      Tags:
        - Key: Name
          Value: aws-study-EC2
