- name: Install SpringBoot
  hosts: mainservers
  become: true
  tasks:
    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Uproad myapp.jar
      ansible.builtin.copy:
        src: app/myapp.jar
        dest: /app/myapp.jar
        mode: '0644'

    - name: Uproad myapp-plain.jar
      ansible.builtin.copy:
        src: app/myapp-plain.jar
        dest: /app/myapp-plain.jar
        mode: '0644'

    - name: Create systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/myapp.service
        mode: '0644'
        content: |
          [Unit]
          Description=Java Application myapp
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/app
          ExecStart=/usr/bin/java -cp /app/myapp-plain.jar:/app/myapp.jar com.example.demo.DemoApplication
          SuccessExitStatus=143
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Restart myapp
      ansible.builtin.systemd:
        name: myapp
        state: restarted
        enabled: true
