- name: Install Java 21 with alternatives
  hosts: ec2
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: java-21-amazon-corretto-devel
        state: present
