name: Ansible

on:
  pull_request:
    paths:
      - 'Ansible/*.yaml'
      - 'Ansible/*.ini'
      - 'terraform/module/**/*.tf'
      - '.github/workflows/Terraform-CI'
      - '.github/workflows/Ansible.yaml'
    types: [opened,synchronize,reopened]

  push:
    branches:
      - main
    paths:
      - 'Ansible/*.yaml'
      - 'terraform/module/**/*.tf'

jobs:
  install-java:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i Ansible/inventory.ini Ansible/install_java.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
