name: Terraform CI

on:
  pull_request:
    paths:
      - 'terraform/module/**/*.tf'
      - 'terraform/environments/**/**.tftest.hcl'
      - '.github/workflows/Terraform-CI.yaml'
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main
    paths:
      - 'terraform/module/**/*.tf'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: terraform/environments/chapter33
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Write test.tfvars
        run: |
          cat <<EOF > test.tfvars
          ${{ secrets.TEST_TFVARS }}
          EOF
      
      - name: Terraform Init (with S3 buckend)
        run: terraform init -reconfigure
      
      - name: Terraform Test
        run: terraform test -var-file test.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file test.tfvars
  
  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: terraform/environments/chapter33
      
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Write test.tfvars
        run: |
            cat <<EOF > test.tfvars
            ${{ secrets.TEST_TFVARS }}
            EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -var-file test.tfvars -auto-approve

        