name: Terraform CI

on:
  pull_request:
    paths:
      - 'terraform/module/alb/**.tf'
      - 'terraform/module/ec2/**.tf'
      - 'terraform/module/monitoring/**.tf'
      - 'terraform/module/network/**.tf'
      - 'terraform/module/rds/**.tf'
      - 'terraform/module/waf/**.tf'
      - 'terraform/environments/**.tftest.hcl'
      - '.github/workflows/*.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: terraform/environments/chapter33
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12.1

      - name: Write test.tfvars
        run: |
          cat <<EOF > test.tfvars
          ${{ secrets.TEST_TFVARS }}
          EOF
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Test
        run: terraform test -var-file test.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file test.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file test.tfvars -auto-approve
